GET http://localhost:3000/todos


###
POST http://localhost:3000
Content-Type: application/json

{
    "text": "my second todo!"
}

###
PUT http://localhost:3000/todo/1696908103350
Content-Type: application/json

{
    "text": "updated todo!"
}

###
DELETE http://localhost:3000/todo/1696908103350